### ISSUE TITLE
Поднятие шпаги на клавишу "вниз".

### ISSUE THREAD

**Issue by Yngwarr** [Order-of-NOP/web-fencing#19]
Собственно, сабж. Давайте придерживаться ~~оригинала~~ традиций.

**Comment by komnotmr** [comment]
Мы и не отклонялись от оригинала пока что. Просто идём поэтапно и для дебага сделали другую клавишу. Как только закончим атаку игрока и бросок шпаги, пропишем нормальное поднятие шпаги.

**Comment by Yngwarr** [comment]
Окей, создал задачу, дабы не забыть.
