### ISSUE TITLE
Объект "Игрок"

### ISSUE THREAD

**Issue by Yngwarr** [Order-of-NOP/web-fencing#2]
Предлагаю сделать его простым как палка. Никаких заморочек с классами -- просто:

```javascript
var player_one = {
    texture: /*...*/,
    jump: function() {/*...*/},
    /*...*/
}
```

**Comment by komnotmr** [comment]
Я наоборот за классы. У них простой синтаксис. 
```javascript
Class Player
{
    Constructor(/*.....*/)
    {
    /*...*/
    }

    jump()
    {
    /*.....*/
    }
}
```

**Comment by Yngwarr** [comment]
@komnotmr, дело в том, что классы в JS работают совсем не так, как в Java или C++ и это может однажды испортить нам жизнь. Пруфы найду позже.

**Comment by Yngwarr** [comment]
Хотя... Можно и классом.

**Comment by komnotmr** [comment]
Сделал так, как предлагал ты. В данном случае это оказалось проще.

**Comment by Yngwarr** [comment]
@komnotmr, на стадии прототипа можно и так, да.

**Comment by Yngwarr** [comment]
Done.
