### ISSUE TITLE
Возможность перепрыгнуть противника

### ISSUE THREAD

**Issue by Yngwarr** [Order-of-NOP/web-fencing#20]
И вообще, стоит настроить физику, дабы игралось комфортно и весело.

**Comment by komnotmr** [comment]
Погоди, ща настроим.

**Comment by komnotmr** [comment]
У нас возникла следующая проблема - при увеличении константы power_jump в player.js больше 2350, персонаж вообще не прыгает. Это какая то магия. Нужно разобраться.

**Comment by komnotmr** [comment]
Игорь, почитай доки по аркадной физике. Там с velocity магия какая то. Я выше писал, что больше 2350 не ставится. Возможно мы что то упускаем в тоннах английского текста.
