### ISSUE TITLE
Расположение надписей

### ISSUE THREAD

**Issue by Yngwarr** [Order-of-NOP/web-fencing#21]
Сейчас надписи "this game" и "pause" расположены криво.

**Comment by komnotmr** [comment]
до тех пор, пока не доберёмся до локации и не выберем размер окна, не пофиксим

**Comment by Yngwarr** [comment]
Хорошо. Пока не срочно.

**Comment by Yngwarr** [comment]
[починено](https://github.com/Order-of-NOP/web-fencing/pull/39)
