### ISSUE TITLE
Подгрузка шрифтов

### ISSUE THREAD

**Issue by komnotmr** [Order-of-NOP/web-fencing#24]
Игорь, сделай подгрузку шрифтов через fontFace, а то грузятся как попало.

**Comment by Yngwarr** [comment]
Хорошо, сделаю. Пока оставлю тут вот [эту ссылку](http://www.magratheaworks.net/RPG/messages_collection/index.html).

**Comment by Yngwarr** [comment]
Теперь надписи грузятся в разметке ([линк](https://github.com/Order-of-NOP/web-fencing/pull/39)).
