### ISSUE TITLE
Основные игровые состояния (Меню, Игра, Настройки) и GUI.

### ISSUE THREAD

**Issue by komnotmr** [Order-of-NOP/web-fencing#3]
Пилим `switch`  в `update` на три игровых состояния: 'меню', 'игра', 'настройки'.
Попробую подобрать какие нибудь пиксельные шрифты, раскидать кнопки в состояниях 'меню' и 'настройки'..

**Comment by komnotmr** [comment]
![image](https://cloud.githubusercontent.com/assets/20460576/22960326/52dd7ce4-f36f-11e6-99a0-ec9f93041000.png)
Нашёл такие шрифты. Не пиксельные, но очень похожи на шрифты из nidhogg. Оставляем или поискать другие ?

**Comment by Yngwarr** [comment]
Пока можно оставить. Вообще, сейчас шрифты -- это далеко не самое главное.

**Comment by Yngwarr** [comment]
[сделано](https://github.com/Order-of-NOP/web-fencing/pull/38)
